back/back/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url, include
from django.shortcuts import render
# from django_email_verification import urls as mail_urls
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('profiles/', include('profiles.urls')),
    path('api/', include('products.api.urls')),
    path('api/', include('cart.api.urls')),
    path('api/', include('wishlist.api.urls')),
    path('supplier/', include('supplier.urls')),
    path('payment/', include('payments.urls')),
    path('api/', include('orders.api.urls')),
    path('api/', include('reviews.api.urls')),
    #url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

back/products/api/urls.py
# from django.urls import path, include
# from rest_framework.routers import SimpleRouter
# from products.api.views import ProductViewSet,CategoryViewSet

# router = SimpleRouter()
# router.register("categories",CategoryViewSet)
# router.register("products", ProductViewSet)

# urlpatterns = [path("", include(router.urls)),
# ]
from django.urls import path, include
from rest_framework.routers import SimpleRouter
from products.api.views import ProductList, CategoryViewSet, ProductDetail
from products.views import *
router = SimpleRouter()
router.register("categories", CategoryViewSet)
# router.register("products", ProductViewSet)

urlpatterns = [
    path('products/', ProductList.as_view(), name='product-list'),
    path('products/<int:pk>', ProductDetail.as_view(), name='product-detail'),
    path('searchhome/', searchhome, name='search-home'),

]

back/products/models.py
from django.db import models
from django.utils import timezone
from django.contrib.postgres.fields import ArrayField
from supplier.models import Supplier_Account
from multiupload.fields import MultiFileField, MultiMediaField, MultiImageField


class Category(models.Model):
    title = models.CharField(max_length=100, unique=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
        ordering = ['title']

    def __str__(self):
        return self.title


class Product(models.Model):
    category = models.ManyToManyField(Category, blank=False)
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    slug = models.SlugField(max_length=200)
    description = models.CharField(max_length=250)
    discount = models.DecimalField(max_digits=9, decimal_places=2, default=0)
    staffRecommended = models.BooleanField(default=False)
    supplier = models.ForeignKey(Supplier_Account, on_delete=models.CASCADE)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name

    @property
    def is_staffRecommended(self):
        return self.staffRecommended


class Size(models.Model):
    size = models.CharField(max_length=50)

    def __str__(self):
        return self.size


class Color(models.Model):
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.color


class Product_Size_Color(models.Model):
    STATUS_CHOICES = (
        ('default', 'DEFAULT'),
        ('updated', 'UPDATED'),
        ('deleted', 'DELETED'),
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.IntegerField()
    status = models.CharField(
        max_length=50, choices=STATUS_CHOICES, default='default')

    class Meta:
        unique_together = (('product', 'size', 'color'))

    def __str__(self):
        return self.product.name


class Product_Images(models.Model):
    product_size_color = models.ForeignKey(
        Product_Size_Color, on_delete=models.CASCADE)
    Image = models.ImageField(upload_to='product/images')


class Product_History(models.Model):
    product_size_color = models.ForeignKey(
        Product_Size_Color, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=9, decimal_places=2)
    quantity = models.IntegerField()
    datetime = models.DateTimeField()

    def __str__(self):
        return self.product_size_color.product.name

back/products/api/views.py
from rest_framework.permissions import AllowAny
from rest_framework import viewsets
from rest_framework.filters import SearchFilter, OrderingFilter
from rest_framework.authtoken import views
from rest_framework import viewsets, status
from rest_framework.response import Response
from .serializers import CategorySerializer, ProductSerializer
from products.models import Product_Size_Color, Category, Product, Product_Images
from django.views.decorators.csrf import csrf_exempt
from rest_framework.renderers import TemplateHTMLRenderer
from wishlist.models import Wishlist
from reviews.models import Reviews
from rest_framework.views import APIView
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from django.core.paginator import Paginator


class CsrfExemptSessionAuthentication(SessionAuthentication):

    def enforce_csrf(self, request):
        return  # To not perform the csrf check previously happening


class CategoryViewSet(viewsets.ModelViewSet):
    queryset = Category.objects.all()
    serializer_class = CategorySerializer


'''
class ProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    # permission_classes = [permissions.IsAuthenticated, ]
    serializer_class = ProductSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["category__title", "name", "description"]

class ParentProductViewSet(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    # permission_classes = [permissions.IsAuthenticated, ]
    serializer_class = ParentProductSerializer
    filter_backends = [SearchFilter, OrderingFilter]
    search_fields = ["category__name", "name", "description","staffRecommended","brand"]
'''
# class ProductViewSet(viewsets.ModelViewSet):
#     queryset = Product.objects.all()
#     permission_classes=(AllowAny,)
#     # permission_classes = [permissions.IsAuthenticated, ]
#     serializer_class = ProductSerializer
#     filter_backends = [SearchFilter, OrderingFilter]
#     search_fields = ["category__title", "name", "description"]
#     ordering_fields = ("category__title", "name", "product_size_color__price")

#     def create(self,request):
#         serializer=ProductSerializer(data=request.data)
#         if serializer.is_valid():
#             print('##############################################')
#             serializer.save()
#             print(serializer.data)
#             return Response(serializer.data, status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class ProductList(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = ProductSerializer
    template_name = "products/index.html"
    authentication_classes = (
        CsrfExemptSessionAuthentication, BasicAuthentication)

    @csrf_exempt
    def get(self, request):
        queryset = Product.objects.all()
        prod = []
        for product in queryset:
            psc = Product_Size_Color.objects.filter(product=product)
            
            obj = Product_Images.objects.filter(product_size_color=psc[0])[0]
            print(obj)
        
            prod.append((product, psc, obj))
        paginator = Paginator(prod, 5)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return Response({'page_obj': page_obj})


class ProductDetail(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    serializer_class = ProductSerializer
    template_name = "products/detail.html"
    # authentication_classes = (CsrfExemptSessionAuthentication, BasicAuthentication)
    # @csrf_exempt

    def get(self, request, pk):
        queryset = Product.objects.get(pk=pk)
        psc = Product_Size_Color.objects.filter(product=queryset)
        review = Reviews.objects.filter(product=pk)
        prod = []
        for p in psc:
            obj = Product_Images.objects.filter(product_size_color=p)
            prod.append((p, obj))
            if request.auth:
                wishlists = Wishlist.objects.filter(owner=request.user)
            else:
                wishlists = []
        return Response({'product': queryset, 'psc': prod, 'wishlists': wishlists, 'reviews': review})

# https://stackoverflow.com/questions/41094013/when-to-use-serializers-create-and-modelviewsets-create-perform-create

back/products/views.py
from django.shortcuts import render
from .models import Product_Size_Color, Product, Size, Color, Category
from django.db import connection
from .filters import ProductFilterHome, ProductFilter
from django.core.paginator import Paginator

# Create your views here.


# def view_products(request):
#     products = Product_Size_Color.objects.prefetch_related(
#         'product__category').all()
#     abc = []
#     for pr in products:
#         cat = pr.product.category.all()
#         abc.append((pr, cat))
#     paginator = Paginator(abc, 1)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)
#     return render(request, "prod.html", {'products': abc})


def searchhome(request):
    product_list = Product.objects.all()
    query = request.GET.get('q', False)
    if query:
        request.session['query'] = query
    product_filter = ProductFilterHome(request.GET, queryset=product_list)
   # product_filter = ProductFilterHome(query, queryset=product_list)
    filter_on = ProductFilter(request.GET, queryset=product_filter.qs)

    paginator = Paginator(filter_on.qs, 5)
    page = request.GET.get('page')
    response = paginator.get_page(page)
    return render(request, 'products/search.html', {'sizes': Size.objects.values('size'), 'colors': Color.objects.values('color'), 'cats': Category.objects.values('title'), 'brands': product_list.values('brand'), 'filter': response, 'filterform': product_filter, 'filter2': filter_on, 'q': query})

back/templates/products/detail.html
<!DOCTYPE html>
<html class="no-js">
    <head>
        <meta charset="utf-8">
        <title></title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <script src="https://use.fontawesome.com/4e5a0a5b55.js"></script>
    </head>
    <body>
      <!-- Button trigger modal -->
<!-- Modal -->
{% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.name|upper }}<br>
    ...
{% endfor %}


{% comment %} <div class="pagination">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
    
            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
    
            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
 {% endcomment %}


{% if user.is_authenticated %}
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Select the wishlist to add the product</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <ul class="list-group">
          {% for wishlist in wishlists %}

              <li class="list-group-item d-flex justify-content-between align-items-center">

                  <p>

                    {{wishlist.name}}

                    <button class="btn btn-primary ml-5 " data-dismiss="modal" aria-label="Close" id='{{wishlist.id}}' onclick="add(this,{{product.id}})" >Add to this wishlist</button>

                  </p>

              </li>

          {% endfor %}
      </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>

      </div>
    </div>
  </div>
</div>
<h5 >{{product.name}}

       <button class="btn btn-warning" id="{{product.id}}" style="float: right;" data-toggle="modal" data-target="#exampleModalCenter">add to wishlist</button>
      </h5>
<div>
<span id='totalScore'></span><i class="fa fa-star"></i>
</div>
<div class="container mt-5">
      <h5 >{{product.name}}</h5>
      <p >{{product.description}}</p>
      {%for item in psc%}
      <div id="{{item.0.id}}">
        <h3>{{item.0.price}}</h3><br><span>{{item.0.size.size}}</span><br><span>{{item.0.color.color}}</span><br>
        {% for img in item.1 %}
          <img src="{{img.Image.url}}" height="100px" width="100px"/><br /><br />
        {% endfor %}
        <input type="number" min="1" step="1" value="1" id='q{{item.0.id}}'>
        <input type="button" class='addEle btn btn-primary' id='{{item.0.id}}' max="{{item.0.quantity}}" value="Add to cart" onclick='sendAddResponse({{item.0.id}})'  style="float: right;"></p>
      
      </div>
      {%endfor%}

    </div>
{%else%}
<h5 >{{product.name}}

         <a href='/accounts/login/?next={{request.path}}' class="btn btn-primary" id="{{product.id}}" style="float: right;">Login in order to add to wishlist</a>
      </h5>
<div class="container mt-5">
      <h5 >{{product.name}}</h5>
      <p >{{product.description}}</p>
      {%for item in psc%}
      <div id="{{item.0.id}}">
        <h3>{{item.0.price}}</h3><br><span>{{item.0.size.size}}</span><br><span>{{item.0.color.color}}</span><br>
        {% for img in item.1 %}
          <img src="{{img.Image.url}}" height="100px" width="100px"/><br /><br />
        {% endfor %}
      <input type="number" min="1" step="1" value="1" id='qty{{item.0.id}}'>
      <a class='btn btn-primary' href='/accounts/login/?next={{request.path}}'>Add to Cart</a>
      </div>
      {%endfor%}

    </div>
{%endif%}

<div class="container mt-5">
<h2>Reviews</h2>
<div class='mt-5'>
  <label for="userrating">Rating:</label>

  <select name="userrating" id="userrating">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
  </select>
<textarea rows="4" cols="50" required></textarea><button class="btn btn-primary" id='review'>Add Review</button>
</div>
<ul class='list-group mt-3 mb-5'>
{%for review in reviews%}
  <div>
  <li class='list-group-item'>{{review.detail}} by {{review.user.customer_profile.firstname}} {{review.user.customer_profile.lastname}} at {{review.created_at}}</li>
  <p>{{review.userrating}}<i class="fa fa-star"></i></p>
  {%if request.user == review.user%}
  <button class='btn btn-danger DelReview' id='{{review.id}}' >Delete Review</button>
  {%endif%}
  </div>
{%endfor%}
</ul>
</div>
<script>
  let totalRating=0
  let i=0
  {%for review in reviews%}
    totalRating+={{review.userrating}}
    i+=1
  {%endfor%}
  let netRating=totalRating/i
  netRating=netRating.toFixed(1)
  console.log(netRating)

  const totalScore=document.getElementById('totalScore')
  totalScore.innerHTML=netRating.toString()
  const addTOCart=document.getElementsByClassName('addEle')
  const addReview=document.getElementById('review')
  const delReview=document.getElementsByClassName('DelReview')
  function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}
  function add(obj,id){
    (async () => {
          let csrftoken = getCookie('csrftoken');
          console.log(csrftoken)
          var url='/api/wishlists/'+obj.id+'/add_to_wishlist/'
          const rawResponse = await fetch(url, {
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
              'X-CSRFTOKEN': csrftoken
            },
            body: JSON.stringify({id:id})
          });
          const content = await rawResponse.json();
          alert('Item added to wishlist')
          //console.log(content);
        })();
  }
  function sendAddResponse(val){
    (async () => {
          var qty='q'+val
          console.log(qty)
          const quant=document.getElementById(qty)
          qty=quant.value
          let csrftoken = getCookie('csrftoken');
          console.log(csrftoken)
          const rawResponse = await fetch('/api/cart/add_to_cart/', {
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
              'X-CSRFTOKEN': csrftoken
            },
            body: JSON.stringify({id:val,quantity:qty})
          });
          
            const content = await rawResponse.json();
            if(content.status=='fail')
              alert('requested quantity not available')
            else
              alert('Item added to cart')
    

          //console.log(content);
        })();
  }

  function postReview(e){
    (async () => {
          const content=document.getElementsByTagName('textarea')[0]
          const userrating=document.getElementById('userrating').value
          let csrftoken = getCookie('csrftoken');
          console.log('{{product.id}}')
          pid='{{product.id}}'
          if(content.value.length < 10){
            alert('Write More')
            return 
          }
          const rawResponse = await fetch('/api/reviews/', {
            method: 'POST',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
              'X-CSRFTOKEN': csrftoken
            },
            body: JSON.stringify({id:pid,"userrating":userrating,"detail":content.value.toString()})
          });
          const contents = await rawResponse.json();
          //console.log(content);
        })();
        location.reload()
  }

  function deleteReview(e){
    (async () => {
          let csrftoken = getCookie('csrftoken');
          const rid=this.id
          console.log(rid)
          const rawResponse = await fetch('/api/reviews/'+rid, {
            method: 'DELETE',
            headers: {
              'Accept': 'application/json',
              'Content-Type': 'application/json',
              'X-CSRFTOKEN': csrftoken
            },
          });

          if(rawResponse.ok){
          location.reload()
          }
          //console.log(content);
        })();
      
      
  }

  addReview.addEventListener('click', postReview)
  for(let i=0;i<delReview.length;i++){
    delReview[i].addEventListener('click',deleteReview)
    console.log(delReview[i].id)
  }
 </script>


</body>
</html>

back/templates/products/index.html
<!DOCTYPE html>
<html class="no-js">

<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
</head>

<body>
    <div class="pagination">
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>
        
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    

    <div class="container mt-5">
        <div class="card-deck">
            {%for product in page_obj %}
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <img src="{{product.2.Image.url}}" height="50px" width="50px"/>
                        <a href="/api/products/{{product.0.id}}"><h5 class="card-title">{{product.0.id}}-{{product.0.name}}</h5></a>
                        <p class="card-text">{{product.0.description|truncatechars:50}}</p>
                    </div>
                </div>
            </div>
            {%endfor%}

        </div>
        <!-- 
        <script>
            const temp=JSON.parse("{{ products|escapejs }}"); for(let i=0;i
            <temp.length;i++){ console.log(temp[i]) } // console.log(temp) const prod=[] const url='/api/products' fetch(url) .then(temp=>temp.json()) .then(data=>prod.push(...data)) console.log(prod)
        </script>
        -->
</body>

</html>

back/templates/products/search.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
{%load bootstrap %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" method="get">
      {{filterform.form|bootstrap}}
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
{% block content %}
{% endblock %}

<div class="pagination">
  <div class="pagination">
      <span class="step-links">
          {% if filter.has_previous %}
              <a href="?page=1{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">&laquo; first</a>
              <a href="?page={{ filter.previous_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">previous</a>
          {% endif %}

          <span class="current">
              Page {{ filter.number }} of {{ filter.paginator.num_pages }}.
          </span>
  
          {% if filter.has_next %}
              <a href="?page={{ filter.next_page_number }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">next</a>
              <a href="?page={{ filter.paginator.num_pages }}{% for key,value in request.GET.items %}{% ifnotequal key 'page' %}&{{ key }}={{ value }}{% endifnotequal %}{% endfor %}">last &raquo;</a>
          {% endif %}
      </span>
  </div>
<div class="container mt-5">
<div class='row'>
<div class='col-md-4'>
<form class="form-inline my-2 my-lg-0" method="get">
  <select  name="category" id="id_category">
    <option value="">Filter Category</option>
    {% for cat in cats %}
    <option value="{{cat.title}}">{{cat.title}}</option>
    {%endfor%}
  </select>
  <select name="max_price" id="id_max_price">
    <option value="">Filter Price Max.</option>
    <option value="100"><100 </option>
    <option value="500"><500</option>
    <option value="1000"><1000</option>
    <option value="3000"><3000</option>
    <option value="5000"><5000</option>
  </select>
  <select  name="brand" id="id_brand">
    <option value="">Filter Brands</option>
    {% for brand in brands %}
    <option value="{{brand.brand}}">{{brand.brand}}</option>
    {%endfor%}
  </select>
  <select name="color" id="id_color">
    <option value="">Filter Color</option>
    {% for color in colors %}
    <option value="{{color.color}}">{{color.color}}</option>
    {%endfor%}
  </select>
  <select name="size" id="id_size">
    <option value="">Filter Size</option>
    {% for size in sizes %}
    <option value="{{size.size}}">{{size.size}}</option>
    {%endfor%}
  </select>
  <input name="q" value='{{q}}' hidden>
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Filter</button>
</form>
</div>
<div class="col-md-8 mt-5">
  <div class='row'>
{% for product in filter %}
  <div class='col-md-4'>
  <div class='card'>
  <img class='card-img-top' src='{{product.product_set.0.product_size_color_set.0.Image.url}}' >
  <div class="card-body">
  <a href='/api/products/{{product.id}}'>{{ product.name }} - {{ product.brand }}</a>
  </div></div>
  </div>
{% endfor %}
</div></div>
</div></div>


</body>
</html>